/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exregan;

import Analyzers.Parser;
import static exregan.MasterMindUI.ch;
import static exregan.MasterMindUI.conjs;
import static exregan.MasterMindUI.filesManipulationHandler;
import static exregan.MasterMindUI.regularExpressions;
import static exregan.MasterMindUI.textEdition1;
import static exregan.MasterMindUI.textEdition2;
import static exregan.MasterMindUI.wordsList;
import java.io.File;
import java.io.IOException;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import javax.swing.JTree;

/**
 *
 * @author Jose
 */
public class GUI extends javax.swing.JFrame {
    static Files_Manipulation filesManipulationHandler = new Files_Manipulation();
    public static  JTextArea textEdition1;
    public static  JTextArea textEdition2;
    public static Error_DAO errorDaoHandler=Error_DAO.getInstance();
    public static java.util.List<Node> regularExpressions = new ArrayList();
    public static java.util.List<Manager> conjs;
    public static String wordsList;
    public static StackList ch;
    public static JTree archivesTree = new JTree();
    public static java.util.List<Statement> statements = new ArrayList();
    public static String response="";
    public static int math =0;
    /**
     * Creates new form GUI
     */
    public GUI() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_Errores = new javax.swing.JButton();
        btn_Reportes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        newButton = new javax.swing.JButton();
        saveAsButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();
        btnAnalizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaSalida = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextAreaEntrada = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pryecto1 José López");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.black);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        btn_Errores.setBackground(new java.awt.Color(51, 255, 255));
        btn_Errores.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btn_Errores.setForeground(new java.awt.Color(0, 0, 0));
        btn_Errores.setText("HTML Errores");

        btn_Reportes.setBackground(new java.awt.Color(51, 255, 255));
        btn_Reportes.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btn_Reportes.setForeground(new java.awt.Color(0, 0, 0));
        btn_Reportes.setText("Generar Reportes");
        btn_Reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReportesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reportes");

        newButton.setBackground(new java.awt.Color(51, 255, 255));
        newButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        newButton.setForeground(new java.awt.Color(0, 0, 0));
        newButton.setText("Nuevo Archivo");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        saveAsButton.setBackground(new java.awt.Color(0, 255, 255));
        saveAsButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        saveAsButton.setForeground(new java.awt.Color(0, 0, 0));
        saveAsButton.setText("Guardar Como");
        saveAsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsButtonActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(0, 255, 255));
        saveButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        saveButton.setForeground(new java.awt.Color(0, 0, 0));
        saveButton.setText("Guardar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        openButton.setBackground(new java.awt.Color(102, 255, 255));
        openButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        openButton.setForeground(new java.awt.Color(0, 0, 0));
        openButton.setText("Abrir");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        btnAnalizar.setBackground(new java.awt.Color(51, 255, 255));
        btnAnalizar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnAnalizar.setForeground(new java.awt.Color(0, 0, 0));
        btnAnalizar.setText("Analizar Entrada");

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Salidas");

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        TextAreaSalida.setBackground(new java.awt.Color(255, 255, 255));
        TextAreaSalida.setColumns(20);
        TextAreaSalida.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        TextAreaSalida.setForeground(new java.awt.Color(0, 0, 0));
        TextAreaSalida.setRows(5);
        jScrollPane2.setViewportView(TextAreaSalida);

        TextAreaEntrada.setBackground(new java.awt.Color(255, 255, 255));
        TextAreaEntrada.setColumns(20);
        TextAreaEntrada.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        TextAreaEntrada.setForeground(new java.awt.Color(0, 0, 0));
        TextAreaEntrada.setRows(5);
        jScrollPane3.setViewportView(TextAreaEntrada);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(openButton)
                        .addGap(33, 33, 33)
                        .addComponent(saveButton)
                        .addGap(40, 40, 40)
                        .addComponent(saveAsButton)
                        .addGap(47, 47, 47)
                        .addComponent(newButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btnAnalizar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btn_Reportes)
                            .addGap(18, 18, 18)
                            .addComponent(btn_Errores))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel1)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveAsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Errores, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
         try {
                            filesManipulationHandler.saveFile(textEdition1.getText());
                        } catch (IOException ex) {
                            Logger.getLogger(MasterMindUI.class.getName()).log(Level.SEVERE, null, ex);
                        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void saveAsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsButtonActionPerformed
        JFileChooser browser = new JFileChooser();
                        browser.setCurrentDirectory(new File("."));
                        browser.setDialogTitle("Select the directory of the new file!!");
                        if(browser.showOpenDialog(saveAsButton) == JFileChooser.APPROVE_OPTION){
                            File SelectBinder = browser.getSelectedFile();
                            System.out.print(filesManipulationHandler.isExpExtension(SelectBinder.getAbsolutePath()));
                            if(filesManipulationHandler.isExpExtension(SelectBinder.getAbsolutePath())){
                                filesManipulationHandler.newFileCreation(SelectBinder.getAbsolutePath(),TextAreaEntrada.getText());
                                filesManipulationHandler.route=SelectBinder.getAbsolutePath();
                            }else{
                                System.out.println("Archive not found");
                            }
                        }
    }//GEN-LAST:event_saveAsButtonActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        JFileChooser browser = new JFileChooser();
                        browser.showOpenDialog(openButton);
                        File file = browser.getSelectedFile();
                        if(file!=null){
                            TextAreaEntrada.setText(filesManipulationHandler.readFile(file.getAbsolutePath()));
                        }
    }//GEN-LAST:event_openButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        TextAreaEntrada.setText("");
    }//GEN-LAST:event_newButtonActionPerformed

    private void btn_ReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReportesActionPerformed
        conjs = new ArrayList();
                        ch = new StackList();
                        Files_Manipulation writer = new Files_Manipulation();

                        wordsList = "";

                        try {
                            String content = TextAreaEntrada.getText();
                            Analyzers.Parser parser;

                            parser = new Analyzers.Parser(new Analyzers.Lexical(new StringReader(content)));
                            parser.parse();

                        } catch (Exception e) {
                        }

                        for(int i=0; i<regularExpressions.size(); i++){
                            String fileName=regularExpressions.get(i).expresionName;
                            
                            java.util.List<Following> followings = new ArrayList(); 
                            Node.theFollowing = followings;
                            Node node = new Node(regularExpressions.get(i),new Node(null,null,"#",regularExpressions.get(i).id+1,"N",
                            Integer.toString(regularExpressions.get(i).getUltimate()),Integer.toString(regularExpressions.get(i).getUltimate()),regularExpressions.get(i).getUltimate())
                            ,".",0,"N","","",0);
                            Parser.root.treeTravel(node);

                            //Crear tabla de siguientes
                            Files_Manipulation.createD(Following.tabulateTheFollowing(followings,fileName),"C:/Users/Jose/Documents/GitHub/OLC1_Proyecto1_1S2023_202100308_C/EXREGAN/Reportes/SIGUIENTES_202100308/"+fileName);

                            //Calcular estados en base a la raíz del arbol
                            State.defineStates(new State(0,node.previous,node.previous.split(","),null));
                            State.usedStates = new ArrayList();
                            
                            java.util.List<State> states = new ArrayList(); 
                            states = State.theStates;
                            //Creación de la tabla de estados

                            Files_Manipulation.createD(State.statesTabulation(states,fileName),"C:/Users/Jose/Documents/GitHub/OLC1_Proyecto1_1S2023_202100308_C/EXREGAN/Reportes/TRANSICIONES_202100308/"+fileName);
                            //AFD
                            Files_Manipulation.createD(State.afdGraph(states),"C:/Users/Jose/Documents/GitHub/OLC1_Proyecto1_1S2023_202100308_C/EXREGAN/Reportes/AFD_202100308/"+fileName);

                            Files_Manipulation.afndCreation(Node.dotAfd, fileName);
                            Node.dotAfd ="";
                            State.theStates.clear(); 
                            Node.terminalList = new ArrayList();

                            //AST
                            writer.treeCreation(node, fileName+Integer.toString(i));
                        }
                        regularExpressions.clear();
                        textEdition2.setText("Autómatas graficados");
    }//GEN-LAST:event_btn_ReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextAreaEntrada;
    private javax.swing.JTextArea TextAreaSalida;
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btn_Errores;
    private javax.swing.JButton btn_Reportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton newButton;
    private javax.swing.JButton openButton;
    private javax.swing.JButton saveAsButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
