
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 23 11:16:23 CST 2023
//----------------------------------------------------

package Analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Word = 9;
  public static final int percent = 3;
  public static final int ExpReg = 26;
  public static final int number = 18;
  public static final int Character = 22;
  public static final int prime = 4;
  public static final int zeroOrMore = 12;
  public static final int questionMark = 15;
  public static final int oneOrMore = 13;
  public static final int twoPoints = 7;
  public static final int closingKey = 6;
  public static final int conj = 8;
  public static final int or = 14;
  public static final int semicolon = 25;
  public static final int greaterThan = 17;
  public static final int line = 16;
  public static final int NumbersList = 10;
  public static final int EOF = 0;
  public static final int point = 11;
  public static final int error = 1;
  public static final int singleQuote = 27;
  public static final int SmallString = 24;
  public static final int Digit = 21;
  public static final int Letter = 20;
  public static final int doubleQuote = 28;
  public static final int lineJump = 29;
  public static final int comma = 2;
  public static final int BigString = 23;
  public static final int LettersList = 19;
  public static final int openingKey = 5;
}

